[package]
name = "tankard_srv"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["typed-header", "typed-routing"] }
axum-htmx = "0.6.0"
headers-accept = "0.1.3"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio", "tls-rustls"] }
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }

[dev-dependencies]
http-body-util = "0.1.2"
scraper = "0.19.0"
serde_json = "1.0.118"
tower = { version = "0.4.13", features = ["util"] }
